export const SellerStyles = {
  GridCards: {
    border: "1px solid black",
    bgcolor: "#272727",
    width: { xs: "180px", lg: "268px" },
    margin: "9px",
    textAlign: "center",
    paddingBottom: "32px",
    borderRadius: "6px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
  },
  GridBoxes: {
    border: "1px solid black",
    bgcolor: "#272727",
    width: { xs: "200px", md: "244" },
    margin: "auto",
    textAlign: "center",
    paddingBottom: "32px",
    borderRadius: "6px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
  },
  GridImage: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: "50%",
    border: "1px solid white",
    width: 100,
    height: 100,
    overflow: "hidden",
    mt: 2,
  },
};
